when:
  - event: [push, pull_request]

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: false
      depth: 0

steps:
  - name: validation
    image: node:20-alpine
    commands:
      - npm ci
      - ./node_modules/.bin/jest --runInBand
