const fs = require('fs-extra');
const path = require('path');

function isTemplatePlaceholder(value) {
    return typeof value === 'string' && /^\{\{[^}]+\}\}$/.test(value.trim());
}

function resolveStartupValue(existing, fallback) {
    if (existing === undefined || existing === null || existing === '') {
        return fallback;
    }

    if (isTemplatePlaceholder(existing)) {
        return fallback;
    }

    return existing;
}

function buildStartupOptions(ctx) {
    const forwardedProto = ctx.headers && ctx.headers['x-forwarded-proto'];
    const forwardedHost = ctx.headers && ctx.headers['x-forwarded-host'];
    const forwardedPort = ctx.headers && ctx.headers['x-forwarded-port'];
    const host = forwardedHost || ctx.host || ctx.hostname || '';
    const proto = forwardedProto || ctx.protocol || '';
    const isTls = proto.toLowerCase() === 'https';
    const portMatch = host.match(/:(\d+)$/);
    const port = forwardedPort ?
        parseInt(String(forwardedPort).split(',')[0].trim(), 10) :
        (portMatch ? parseInt(portMatch[1], 10) : NaN);

    return {
        server: host.replace(/:\d+$/, '') || ctx.hostname || '',
        port: Number.isFinite(port) && port > 0 ? port : (isTls ? 443 : 80),
        tls: isTls,
        direct_path: ctx.basePath || '/',
    };
}

module.exports = function(app, oauthClientConf) {
    let router = app.webserver.router;

    let publicPath = app.conf.relativePath(app.conf.get('webserver.public_dir'));

    router.get('kiwi.bnc_plugin', '/kiwibnc_plugin.html', async (ctx, next) => {
        ctx.body = await fs.readFile(
            path.join(__dirname, 'kiwibnc_plugin.html'),
            { encoding: 'utf8' },
        );
    });

    router.get('kiwi.config', '/static/config.json', async (ctx, next) => {
        let config = await fs.readFile(path.join(publicPath, 'static', 'config.json'));
        config = JSON.parse(config);
        config = {
            ...config,
            '## comment': 'Auto generated by KiwiBNC',
            kiwiServer: '',
            startupScreen: 'kiwibnc',
        };

        const requestStartupOptions = buildStartupOptions(ctx);
        config.startupOptions = {
            ...config.startupOptions,
            server: resolveStartupValue(config.startupOptions.server, requestStartupOptions.server),
            port: resolveStartupValue(config.startupOptions.port, requestStartupOptions.port),
            tls: resolveStartupValue(config.startupOptions.tls, requestStartupOptions.tls),
            direct_path: resolveStartupValue(
                config.startupOptions.direct_path,
                requestStartupOptions.direct_path
            ),
            direct: true,
            channel: '',
            bouncer: true,
            remember_buffers: false,
            public_register : app.conf.get('webchat.public_register', false),
        };

        // Add our kiwi plugin to the config
        config.plugins = config.plugins || [];
        config.plugins.push({
            name: 'kiwibnc',
            url: router.url('kiwi.bnc_plugin', {}),
            basePath: ctx.basePath,
        });

        if (oauthClientConf) {
            config.oauth = oauthClientConf;
        }

        let extraConf = app.conf.get('webchat');
        for (let prop in extraConf) {
            config[prop] = extraConf[prop];
        }

        ctx.body = config;
    });

    app.webserver.router.post('kiwi.config', '/api/register', async (ctx, next) => {
        if (!app.conf.get('webchat.public_register', false)) {
            ctx.body = {error: 'forbidden'};
            return;
        }

        let body = ctx.request.body;
        if (!body.username || !body.password) {
            ctx.body = {error: 'missing_params'};
            return;
        }

        if (await app.userDb.getUser(body.username)) {
            ctx.body = {error: 'username_in_use'};
            return;
        }

        let admin = false;

        // If this is the first user, make them an admin
        let usersExist = await app.db.factories.User.query().first();
        if (!usersExist) {
            admin = true;
        }

        try {
            let user = await app.userDb.addUser(body.username, body.password, admin);
        } catch (err) {
            if (err.message === 'Invalid username') {
                ctx.body = {error: 'invalid_username'};
            } else {
                ctx.body = {error: 'unknown_error'};
            }

            return;
        }

        ctx.body = {error: false};
    });
};
